### ISSUE TITLE
Change user-facing naming from "Secrets" to "Passwords"

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-app2#108]
The user-facing name should for the secrets-app should be "Passwords", at least the following occurrences should be changed:
* [ ] Change tab name from "Secrets" to "Passwords"
* [ ] "Show Protected Secrets" -> "Show Protected Passwords"

**Comment by robin-nitrokey** [comment]
The how to we call the actual login and password that we will add in the future?  “Static password”?
