### ISSUE TITLE
Cannot upgrade/use Nitrokey 3 under Fedora 

### ISSUE THREAD

**Issue by jasperjonker** [Nitrokey/nitrokey-app2#121]
I'm trying to upgrade the firmware on the Nitrokey 3, but this doesn't seem possible.
After downloading the v2.0.1 release and executing, I get the following error:
```sh
$ ./nitrokey-app-v2.0.1-x64-linux-binary
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
libEGL warning: MESA-LOADER: failed to open iris: /tmp/_MEIG4jMEE/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib64/dri/iris_dri.so) (search paths /usr/lib64/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: /tmp/_MEIG4jMEE/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib64/dri/swrast_dri.so) (search paths /usr/lib64/dri, suffix _dri)

qt.qpa.wayland: Failed to initialize EGL display 3001
```
The window pops up and does recognize that there is a Nitrokey 3 with firmware `v1.4.0`. However, when pressing the update button (and accept pop-up) to `v1.5.0`, the nitrokey starts blinking, but the app freezes. It asks several time to force-quit the app. Eventually it becomes responsive, but didn't update the firmware.
![image](https://github.com/Nitrokey/nitrokey-app2/assets/44026484/5e72a966-cba7-49b0-88bb-6b50fa22a79a)

By executing `export LD_PRELOAD=/usr/lib64/libstdc++.so.6` the warning in the logs don't show anymore, but no improvements in updating the firmware / getting the nitrokey to work. The app still freezes as well:
```sh
$ export LD_PRELOAD=/usr/lib64/libstdc++.so.6

$ ./nitrokey-app-v2.0.1-x64-linux-binary
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
```

Any idea how I can update the firmware and start using the nitrokey 3?

Version: `v2.0.1`
Os: Fedora 38
Nitrokey 3C NFC

**Comment by jasperjonker** [comment]
I notice that during the moment I press "update", the nitrokey starts blinking. When I press on the nitrokey, it seems to continue, as I get the following error message:
```sh
$ ./nitrokey-app-v2.0.1-x64-linux-binary
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Exception ignored in: <generator object Updater._get_bootloader at 0x7f0891ef4f90>
Traceback (most recent call last):
  File "nitrokeyapp/pynitrokey_for_gui.py", line 221, in nk3_update
RuntimeError: generator ignored GeneratorExit
```

Not sure if one should press the button on the nitrokey, as I never get a message telling me to press it.

**Comment by jasperjonker** [comment]
Seems like issue is related to https://github.com/Nitrokey/nitrokey-app2/issues/73
I didn't had the proper udev rules installed. Using the cli, I could upgrade following [the instructions](https://docs.nitrokey.com/nitrokey3/linux/firmware-update#how-to-update).

Not closing, as the issue with the app isn't solved

**Comment by robin-nitrokey** [comment]
To me it looks like this is related to https://github.com/nitrokey/pynitrokey.  The next app release will improve the logs and add a proper error dialog for unhandled exceptions so it should be easier to figure out what went wrong.

**Comment by bocekm** [comment]
I had a slightly related error on Fedora 38 with my NitroKey 3C when trying to update it from 1.4.0 to 1.5.0:
```
$ ~/Downloads/nitrokey-app-v2.1.2-x64-linux-binary
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Exception ignored in: <generator object Updater._get_bootloader at 0x7f6154122ba0>
Traceback (most recent call last):
  File "nitrokeyapp/device_data.py", line 53, in update
RuntimeError: generator ignored GeneratorExit
```

**Comment by daringer** [comment]
please use the flathub package: https://flathub.org/apps/com.nitrokey.nitrokey-app2 (currently no nk3mini update is possible there currently, will be fixed with one of the next releases)
