### ISSUE TITLE
Ubuntu 22.04 LTS Compatibility

### ISSUE THREAD

**Issue by AnanasPfirsichSaft** [Nitrokey/nitrokey-app2#134]
Hello,

just for the record: I had to set

`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6`

(as in #121) in my terminal emulator before running the nitrokey-app (2.1.2) to avoid this issue

```
Traceback (most recent call last):
File "nitrokeyapp/__main__.py", line 6, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/_MEIDdDaoA/libstdc++.so.6)
[32378] Failed to execute script '__main__' due to unhandled exception!
```

And have /tmp mounted with "exec" (or without "noexec") as other user noticed. I haven't encountered older problems with Wayland ("could not load qt platform plugin") so far. It runs fine. I will test a firmware upgrade with the app when it is available.

**Comment by daringer** [comment]
please use the flathub package: https://flathub.org/apps/com.nitrokey.nitrokey-app2 (currently no nk3mini update is possible there currently, will be fixed with one of the next releases)
