### ISSUE TITLE
Build and Release for macOS

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-app2#135]
We should also build and release a `dmg` for macOS. 
Please :+1: this issue to increase priority.

**Comment by brevilo** [comment]
While at it, *please* make it available as a [Homebrew cask](https://www.nitrokey.com/download/macos) as well, like the first Nitrokey app (tap [broken](https://github.com/Nitrokey/nitrokey-app/issues/496) right now).

**Comment by grumpy-guy** [comment]
Has any progress been made on this topic?

**Comment by daringer** [comment]
As the Password Manager was now [released](https://github.com/Nitrokey/nitrokey-app2/releases/tag/v2.2.1) - we are now working on deployment/distribution - cannot give an ETA yet, but at least it's now on the high priority list

**Comment by daringer** [comment]
currently there are the following blockers for a full macOS release:
* https://github.com/Nitrokey/pynitrokey/issues/145 
* secrets touch confirmation seems not to work
* auto-detection (add/remove device) not working properly
