### ISSUE TITLE
provide information on whether the app itself has the latest version

### ISSUE THREAD

**Issue by Niklap97** [Nitrokey/nitrokey-app2#137]
- It would be easiest for users to find out within the app, so they don't have to research it

**Comment by robin-nitrokey** [comment]
See https://github.com/Nitrokey/pynitrokey/pull/416 for an implementation guideline.

**Comment by daringer** [comment]
I would say we should not do this unattended, it might be not what is expected from such an application to automatically connect to the internet without asking. Maybe a "check for updates" button inside the no-nitrokey-was-selected view
