### ISSUE TITLE
Please do not over-constrain dependencies

### ISSUE THREAD

**Issue by panicgh** [Nitrokey/nitrokey-app2#152]
This [line](https://github.com/Nitrokey/nitrokey-app2/blob/9c41a9aebd7e20de768ab80f639f701a6ab48173/pyproject.toml#L27C4-L27C4) pins pynitrokey to an exact version, which is outdated by now. I cannot update pynitrokey to the latest version and use nitrokey-app2, because it fails to build due to the version constraint.

Please avoid over-constraining dependencies, e.g. pynitrokey, and use version ranges instead (e.g. `>= 0.4.38`, `< 0.5.0`).

**Comment by robin-nitrokey** [comment]
Unfortunately, pynitrokey currently does not use semantic versioning and even patch versions may include breaking changes.  Hopefully, this will change in the future.  But for the time being, I think we have to pin the version to avoid incompatibilities.

**Comment by fapsi** [comment]
Are there any problems regarding 0.4.39 ? I just tested it rudimentary, because of this annoying installation error: https://github.com/Nitrokey/pynitrokey/issues/421

**Comment by robin-nitrokey** [comment]
Not that I’m aware of.  Even 0.4.40 should work fine, see: https://github.com/Nitrokey/nitrokey-app2/pull/149

**Comment by anthraxx** [comment]
Pinning like this makes it quite cumbersome and painful for distros to package this as a repository package. We'd highly appreciate and looking forward to a day where semver in pynitrokey can be applied :cat:

**Comment by robin-nitrokey** [comment]
Since https://github.com/Nitrokey/nitrokey-app2/pull/264 / [v2.3.2](https://github.com/Nitrokey/nitrokey-app2/releases/tag/v2.3.2), we use the [Nitrokey Python SDK](https://github.com/Nitrokey/nitrokey-sdk-py) instead of pynitrokey.  The SDK follows semantic versioning so we only require a semver-compatible version.  I hope this improves the situation.
