### ISSUE TITLE
please make this app a statically compiled one so it includes all dependencies

### ISSUE THREAD

**Issue by commandline-be** [Nitrokey/nitrokey-app2#197]
please make this app a statically compiled one so it includes all dependencies

./nitrokey-app-v2.1.5-x64-linux-binary 
PySide6/__init__.py: Unable to import Shiboken from /tmp/_MEI1vycxs/base_library.zip, /tmp/_MEI1vycxs/lib-dynload, /tmp/_MEI1vycxs
Traceback (most recent call last):
  File "nitrokeyapp/__main__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "PySide6/__init__.py", line 124, in <module>
  File "PySide6/__init__.py", line 64, in _setupQtDirectories
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "shiboken6/__init__.py", line 27, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/_MEI1vycxs/libstdc++.so.6)
[350664] Failed to execute script '__main__' due to unhandled exception!

**Comment by daringer** [comment]
flatpak support is already there - we aim to provide it through flathub with v2.2 ... the single binary won't be continued, obviously not such a good idea for Linux systems

**Comment by daringer** [comment]
the flathub store now contains [nitrokey-app2](https://flathub.org/apps/com.nitrokey.nitrokey-app2), this is now the preferred way of installing the nitrokey-app2 on Linux systems...

**Comment by f403** [comment]
I'd like to reopen this. Flatpack is way too big (2.1G disk space with all dependencies)

**Comment by daringer** [comment]
even though the initial issue has not mentioned binary size - we might for sure discuss this here ...
currently the entire flatpak image is ~300mb ... still too much, but already reduce from idk ~600mb ... we could try to further clean up the qt6 libs at the end of the build - other than that - including dependencies into this calculation is kind of extreme - did you include the linux kernel in your estimation ? xD 

no seriously: if you have a suggestion how we could distribute a smaller static binary, please share - as of now flatpak is for sure the most convenient solution, although obviously not size-optimal

**Comment by f403** [comment]
> rewrite it in [...] (Rust/Go) ?

I didn't want to make that big deal out of this, sorry :)

My issue is now solved with [compilation from source code](https://github.com/Nitrokey/nitrokey-app2?tab=readme-ov-file#compiling-for-linux-and-macos). It is still big (700M after installation and 600M of caches), but I prefer this way.

And even better for me, `nitropy` can do the same (an more) as the UI app

**Comment by daringer** [comment]
closing - and we'll be working in reducing the size - we won't open the "re-write in rust" discussion (for now :D)
