### ISSUE TITLE
[2.2.1] Core dump on exit

### ISSUE THREAD

**Issue by tuxmaster5000** [Nitrokey/nitrokey-app2#215]
On exit the app will crash with an coredump.
OS: Fedora 38
Installed in an virtual python environment.
stack trace:

> Stack trace of thread 65298:
>                                          #0  0x00007f2a89cb0884 __pthread_kill_implementation (libc.so.6 + 0x8e884)
>                                          #1  0x00007f2a89c5fafe raise (libc.so.6 + 0x3dafe)
>                                          #2  0x00007f2a89c4887f abort (libc.so.6 + 0x2687f)
>                                          #3  0x00007f2a798b792c n/a (/home/XXX/pynitrokey/lib/python3.11/site-packages/PySide6/Qt/lib/libQt6Core.so.6 + 0xb792c)
>                                          #4  0x0000000000000000 n/a (n/a + 0x0)
>                                          ELF object binary architecture: AMD x86-64

Console log:
bin/nitrokeyapp 

> Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
> QThread: Destroyed while thread is still running
> Abgebrochen (Speicherabzug geschrieben) / Core dump
> 
It will be enough  starting the app without the NK and exit it to trigger the crash.

**Comment by tuxmaster5000** [comment]
Installed modules:
bin/pip3 list
```
Package             Version
------------------- ----------
appdirs             1.4.4
argparse-addons     0.12.0
asn1crypto          1.5.1
astunparse          1.6.3
bincopy             17.14.5
bitstring           4.0.2
capstone            4.0.2
certifi             2023.11.17
cffi                1.16.0
charset-normalizer  3.3.2
click               8.1.3
click-aliases       1.0.1
click-command-tree  1.1.1
click-option-group  0.5.6
cmsis-pack-manager  0.5.3
colorama            0.4.6
commentjson         0.9.0
crcmod              1.7
cryptography        41.0.7
deepmerge           1.1.0
ecdsa               0.18.0
fastjsonschema      2.17.1
fido2               1.1.2
fire                0.5.0
hexdump             3.3
humanfriendly       10.0
idna                3.6
importlib-metadata  6.8.0
importlib-resources 6.1.1
intelhex            2.3.0
intervaltree        3.1.0
Jinja2              3.1.2
lark                1.1.8
lark-parser         0.7.8
libusb-package      1.0.26.2
libusb1             3.1.0
libusbsio           2.1.11
MarkupSafe          2.1.3
natsort             8.4.0
nethsm              1.0.0
nitrokeyapp         2.2.1
nkdfu               0.2
oscrypto            1.3.0
pip                 24.0
prettytable         3.9.0
protobuf            3.20.3
psutil              5.9.6
pycparser           2.21
pycryptodome        3.18.0
pyelftools          0.30
pylink-square       1.1.0
pynitrokey          0.4.45
pyocd               0.35.1
pyocd-pemicro       1.1.5
pypemicro           0.1.11
pyserial            3.5
PySide6             6.6.1
PySide6-Addons      6.6.1
PySide6-Essentials  6.6.1
python-dateutil     2.7.5
pyudev              0.24.1
pyusb               1.2.1
PyYAML              6.0.1
qt-material         2.14
requests            2.31.0
ruamel.yaml         0.17.40
ruamel.yaml.clib    0.2.8
semver              3.0.2
setuptools          65.5.1
shiboken6           6.6.1
six                 1.16.0
sly                 0.5
sortedcontainers    2.4.0
spsdk               1.11.0
termcolor           2.3.0
tlv8                0.10.0
tqdm                4.66.1
typing_extensions   4.3.0
urllib3             2.0.7
wcwidth             0.2.12
wheel               0.42.0
zipp                3.17.0

```

**Comment by daringer** [comment]
yes, this is kind of known behavior currently - some pyside6 threading issue we didn't manage to solve yet, but usually this shouldn't lead to a core-dump ... we just have observed the error before until now (`QThread: Destroyed while thread is still running`)
