### ISSUE TITLE
Cannot launch nitrokey-app2 

### ISSUE THREAD

**Issue by pescepalla** [Nitrokey/nitrokey-app2#228]
As of version 2.2.2, I am unable to launch the app:

```
$ nitrokeyapp 
Traceback (most recent call last):
  File "/usr/bin/nitrokeyapp", line 5, in <module>
    from nitrokeyapp.__main__ import main
  File "/usr/lib/python3.11/site-packages/nitrokeyapp/__main__.py", line 10, in <module>
    from nitrokeyapp.gui import GUI
  File "/usr/lib/python3.11/site-packages/nitrokeyapp/gui.py", line 11, in <module>
    from pynitrokey.nk3 import Nitrokey3Device
ImportError: cannot import name 'Nitrokey3Device' from 'pynitrokey.nk3' (/usr/lib/python3.11/site-packages/pynitrokey/nk3/__init__.py)

$ pacman -Q nitrokey-app2
nitrokey-app2 2.2.2-1

$ pacman -Q python-pynitrokey
python-pynitrokey 0.4.46-1
```

OS: Arch Linux

**Comment by robin-nitrokey** [comment]
`nitrokey-app2` currently requires `pynitrokey` 0.4.45.  To make sure you always have the right versions, you can install it via Flatpak or using the pre-built binary, see [the documentation](https://docs.nitrokey.com/software/nk-app2/installation_linux), or run it manually, see [the readme](https://github.com/Nitrokey/nitrokey-app2#compiling-for-linux-and-macos).

**Comment by pescepalla** [comment]
Thanks. That was it.
