### ISSUE TITLE
[2.2.2] msi file not signed

### ISSUE THREAD

**Issue by tuxmaster5000** [Nitrokey/nitrokey-app2#230]
When I download the msi file, edge will block the file, because it is not signed.
When force the download, the same error will happens on execution of the file.
It's crazy that software for a security product is classed as unsafe.

**Comment by mmerklinger** [comment]
I just looked into it and you are right. Something went wrong during the upload of the signed files. I just uploaded them again and made sure they are signed now. Unfortunately Microsoft Edge still shows an error when you download them. After downloading you can see the signature in the file properties though. I reported the false warning to Microsoft.

**Comment by daringer** [comment]
closing for now - signed binaries are sadly a constant issue :D please re-open if you still have (major) issues
