### ISSUE TITLE
Release of 2.2.2 or newer version to Flathub

### ISSUE THREAD

**Issue by XSpielinbox** [Nitrokey/nitrokey-app2#234]
The [release of version 2.2.2](https://github.com/Nitrokey/nitrokey-app2/releases/tag/v2.2.2) contains changes, I would really like to have, but it states, that "This release will not be published on flathub. The next release will be published on flathub again and will be released very soon"

This was on the 5th of March, so over a month ago. There is still no release date of 2.3.0 or any sign of 2.2.3. Is there any plan on when this "very soon" release will be or how can one help getting a newer version released as a Flatpak?

**Comment by daringer** [comment]
ahhh, good point, we plan the v2.3 release for the coming week, which will also be released on flathub - sorry for the delays

**Comment by mmerklinger** [comment]
Version 2.3.0 was released on the 2024-04-24.
