### ISSUE TITLE
Enable special case handling in QubesOS

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-app2#240]
To allow proper deployment of the App2 and updates of NK3 devices inside QubesOS.

This should be a multi step approach:
* detect if app2 is run inside QubesOS
* allow to switch device into bootloader
* inform user that they have to re-attach the device in QubesOS (twice)
* tell the user to restart the nitrokey-app2 
* show bootloader device and allow update

**Comment by mmerklinger** [comment]
@daringer Can we close this issue or is there something left to do?

**Comment by daringer** [comment]
not so far I see, thx closing
