### ISSUE TITLE
apps on ubuntu repos

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nitrokey-app2#246]
It looks like there are 2 nitrokey apps on ubuntu repos:

![Screenshot from 2024-05-10 17-45-42](https://github.com/Nitrokey/nitrokey-app2/assets/8382834/602c0150-bb0b-43c5-9c23-1b0dd2e4b9de)

One seems fully "legit / green / safe":

![Screenshot from 2024-05-10 17-46-19](https://github.com/Nitrokey/nitrokey-app2/assets/8382834/48716158-fc34-4d52-a126-9ada8e9a7a2c)

But I do not know what to think about the second one; is it legit or is it "spoofing"?

![Screenshot from 2024-05-10 17-46-43](https://github.com/Nitrokey/nitrokey-app2/assets/8382834/219c49b4-a0ec-40c3-a344-4204838d5b7b)

Also, are these nitrokey app 1 or 2?

**Comment by robin-nitrokey** [comment]
I’m not familiar with the Ubuntu app store but it looks like these two versions come from different sources – see the top right of the window.

> Source: Snap Store (Snap)
> Source: ubuntu-jammy-univer...

From my understanding, the first is the general Snap store and the second is the Snap store for a specific Ubuntu release.

Anyway, with the version number being 1.4.2 for both packages, it’s not Nitrokey App 2 but the [old Nitrokey App](https://github.com/nitrokey/nitrokey-app).

**Comment by mmerklinger** [comment]
The two packages are the Snap from [Snapcraft](https://snapcraft.io/nitrokey-app) and the distribution package from [Ubuntu Jammy](https://packages.ubuntu.com/jammy/nitrokey-app). Both versions contain the old Nitrokey-App (version 1.4). The Nitrokey-App 2 is currently not available as Snap or DEB package and also not on out roadmap.
