### ISSUE TITLE
Unable to update from NK3 v1.5.0 to V1.7.0

### ISSUE THREAD

**Issue by tlaurion** [Nitrokey/nitrokey-app2#249]
Detail and pictures at https://github.com/linuxboot/heads/pull/1684#issuecomment-2122962402

**Comment by nestire** [comment]
hey I see you trying this under Qubes there is an issue https://github.com/QubesOS/qubes-issues/issues/8953  a workaround is in this comment https://github.com/QubesOS/qubes-issues/issues/8953#issuecomment-1957154706, but its not clear how reliable this is. You could also install nitropy Nitrokey App 2 directly in sys-usb or a hvm qube with usb attached. We working on resolving this.

**Comment by nestire** [comment]
here is the PR (should be merged soon) for our documentation https://github.com/Nitrokey/nitrokey-documentation/pull/248

**Comment by tlaurion** [comment]
Will give it a shit tomorrow.

**Comment by mmerklinger** [comment]
@tlaurion Is this still an issue for you?

**Comment by tlaurion** [comment]
![2024-06-13-194150](https://github.com/Nitrokey/nitrokey-app2/assets/827570/b8a339ab-77ec-48bc-8613-d761b033e563)

**Comment by mmerklinger** [comment]
Thanks for the feedback!
