### ISSUE TITLE
Pin Change for Secrets App not Working in 2.3.1

### ISSUE THREAD

**Issue by nestire** [Nitrokey/nitrokey-app2#263]
way to reproduce: 

1. Set Pin (1234)
2. Change Pin to minimize confusion just use the same pin in all field 1234
3. it will ask you 3 times to press the nitrokey but will always Fail with PinValidationError 

Setting the pin with nitropy works without problem.

What expected:

Pin to Change or if wrong current pin was provided to fail after the first try and not retry 3 times  

OS: Qubes 4.2 Fedora 40 Qube

**Comment by kevin0t** [comment]
i am having the same problem with nitrokeyapp2 2.3.1 Though i could observe although it shows us an error output while changing the PIN , the function is actually successful and i found the new pin had been
 set for further functions. In my case i tried to change the password manager pin.
hereby attaching a log - 
[nitrokey_log.txt](https://github.com/user-attachments/files/16673227/nitrokey_log.txt)
