### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by secretmango** [Nitrokey/nitrokey-app2#266]
I wonder if it would be possible to support Android.

Android lacks a lot of support for hardware security keys. On a Google Pixel with the secure element, they may not really be needed for some tasks, but they are for others.

There are people daily driving GrapheneOS and Android tablets may get better and better here.

Is Android support possible? My Nitrokey 3Amini is detected correctly and the OS even has some integration, I am just missing an app.

**Comment by daringer** [comment]
We have not (yet) developed an Android app similar to the NitrokeyApp(2) - but you can use the smartcard features by using open-keychain - recently Nitrokey 3 support was added and is now available. At some point we'll also have a mobile app (iOS has to be taken into account, too) - but currently we cannot estimate when this will happen.
