### ISSUE TITLE
Add your application to standard Debian -APT Reposetory.

### ISSUE THREAD

**Issue by isa10110** [Nitrokey/nitrokey-app2#291]
Using Flathub adds more complexity to your PC setup.  I would like to install security-relevant software at a standard source my operating system provides me.

**Comment by daringer** [comment]
totally understand, currently we focus on distribution via flatpak as its the most user friendly solution - also for non-tech users. Nevertheless we've recently changed the underlying libraries to reduce dependencies and especially `nitrokey-sdk` will likely be available in debian package repositories soon(tm) - once this is done nitrokey-app2 might also be possible. But in the short-term the main distribution method on Linux will be flatpak.
