### ISSUE TITLE
Please add CLI capebilitys to this app

### ISSUE THREAD

**Issue by isa10110** [Nitrokey/nitrokey-app2#292]
I want to use TOTP  and and simple OTP  by only installing the app and not touch  the GUI  of this,  
Please make me that possible to me kind regards.
Isabell

**Comment by robin-nitrokey** [comment]
You can use https://github.com/nitrokey/pynitrokey to access OTP and other features of the Nitrokey 3 from the CLI.

**Comment by isa10110** [comment]
This thing is not feature complete it don't ports totp  and only using OTP  succes

**Comment by isa10110** [comment]
I  Need a tool where I don't have to  build up  my totp  before of using it
