### ISSUE TITLE
Time Exeption don't work Propaly

### ISSUE THREAD

**Issue by isa10110** [Nitrokey/nitrokey-app2#293]
Please add something like a proper working exception if no one presses the activation on the Fido key (Nitro Key 3A NFC)

I used your flatpack build. 

![image](https://github.com/user-attachments/assets/0b1ec17e-6cfa-426c-9896-9a89bcdbb4b1)

[ERROR_log.txt](https://github.com/user-attachments/files/17297681/ERROR_log.txt)

please fix that :)

**Comment by daringer** [comment]
Most of these are caught - thanks for finding a not caught one. But you miss to mention what exactly you've been doing. I did reproduce this behavior like this:
* create a TOTP secret with touch confirmation
* request a OTP
* do not confirm this with a user presence check on the Nitrokey 3
* non-caught error like the above will show up

did you find any other case in which such an error is not caught properly ?

**Comment by isa10110** [comment]
I  installed your app from flathub. 
I created a TOTP key 
saved the key generation. 
tried to  get a totp  key generated. 
I don't pressed the Autentificaton button on the Nitokey 3A NFC
and after a half minute of waiting the app crashed

It's a bad handling of timeout or something possible regarding the Python version you are shipping and the log attached. 

I use a blank  kubuntu for this test Kubuntu 24.04.1 LTS x86_68
probably you can reproduce it there :)

**Comment by isa10110** [comment]
I repuduced that behavior again on a different machine with different keys
