### ISSUE TITLE
Feature Request: Flatpak Support (Linux)

### ISSUE THREAD

**Issue by birds-swim** [Nitrokey/nitrokey-app2#53]
Hello! 

Please consider Flatpak support for your new Nitro App 2. I think this would be the most accessible way for Linux users to enjoy your software. Flatpak has become the de-facto standard across all Linux distros. I think it'd be really great and I would totally use your app on FlatHub.

**Comment by r3tr0-git** [comment]
Is there an ETA or something we can help with?
