### ISSUE TITLE
text not visible in dark mode

### ISSUE THREAD

**Issue by Niklap97** [Nitrokey/nitrokey-app2#59]
- KDE Plasma  
- dark mode displays white text on white background

**Comment by PureTryOut** [comment]
![Screenshot_20230501_131801](https://user-images.githubusercontent.com/1565836/235444883-ebbad0f2-9516-4f90-978e-ac4d29ce68cd.jpg)

**Comment by daringer** [comment]
closed, as duplicate for #58
