### ISSUE TITLE
Nitrokey-app2 v2.0.1 does not run on Fedora 37 (Workstation)

### ISSUE THREAD

**Issue by sja1440** [Nitrokey/nitrokey-app2#68]
When running on a fully updated Fedora 37 Workstation (Wayland) 

$ ./nitrokey-app-v2.0.1-x64-linux-binary 
./nitrokey-app-v2.0.1-x64-linux-binary: error while loading shared libraries: libz.so.1: failed to map segment from shared object

I see no applicable logs in the journal.

Here is the version of libz.so that is being used:
```
ls -l /usr/lib64/libz.so.1
lrwxrwxrwx. 1 root root 14 Aug 31  2022 /usr/lib64/libz.so.1 -> libz.so.1.2.12
```

**Comment by mmerklinger** [comment]
Hey! I just tried to reproduce this with the same version on a fully updated Fedora 37. I didn't see this error. The app works for me. I see some mesa related errors which don't impact the functionality of the app. Is this still an issue for you?

**Comment by robin-nitrokey** [comment]
I think this could be related to the mount options for your `/tmp`  dir.  The Linux binary includes libraries that are extracted to `/tmp` but the `noexec` mount option prevents them from being loaded.  Can you share the output of `findmnt --target /tmp`?

See also: https://github.com/Nitrokey/nitrokey-app2/issues/54

**Comment by sja1440** [comment]
Thanks for the observation. On currently on holiday with no access to
my workstation, I'll be able to try again from the last week of July.

**Comment by mmerklinger** [comment]
Fedora 37 is [end of life since 2023-12-05](https://docs.fedoraproject.org/en-US/releases/eol/). The currently two supported releases should work.
