### ISSUE TITLE
Text practically invisible when using KDE with dark color scheme

### ISSUE THREAD

**Issue by csarn** [Nitrokey/nitrokey-app2#70]
This is what the app looks like: 
![image](https://github.com/Nitrokey/nitrokey-app2/assets/4563314/adf564fa-075c-4a90-a947-daa4ea247b12)

If the app respects the text color settings, it should also respect the background color settings.

**Comment by robin-nitrokey** [comment]
Duplicate of: https://github.com/Nitrokey/nitrokey-app2/issues/58
