### ISSUE TITLE
Crash while updating firmware under wayland.

### ISSUE THREAD

**Issue by Serafean** [Nitrokey/nitrokey-app2#72]
nitrokey-app kills itself while updating firmware under a wayland compositor  (kwin in my case), after the window becoming unresponsive for a wile.

Running with `QT_QPA_PLATFORM=xcb ./venv/bin/nitrokeyapp`  makes it behave more sanely.

**Comment by Serafean** [comment]
Update: It also doesn't show the instruction to "touch the nitrokey"  , so the update actually never got started.

**Comment by mmerklinger** [comment]
I tried to reproduce this, but failed to do so. Generally the application should work on Xorg and Wayland sessions. Please try again with the current [version 2.2.1](https://github.com/Nitrokey/nitrokey-app2/releases/tag/v2.2.1). I will close this for now, but please feel free to reopen with more information (Linux distribution, desktop, and log files), if the problem still persists.
