### ISSUE TITLE
Move to Qt6

### ISSUE THREAD

**Issue by tuxmaster5000** [Nitrokey/nitrokey-app2#93]
Qt5 are EOL (https://en.wikipedia.org/wiki/Qt_version_history)
Only Qt6 are supported without any commercial licence.

**Comment by robin-nitrokey** [comment]
Based on the [changelog](https://www.riverbankcomputing.com/static/Docs/PyQt6/pyqt5_differences.html), it looks like there are only two changes that really affect us: 
- *All named enums are now implemented as a sub-class of the standard Python Enum class.*  This also means that some of the untyped enums have been moved into separate types, but that should be easy to fix.
- *Support for Qt’s resource system has been removed (i.e. there is no `pyrcc6`).*  This means that we should directly package our data with our package manager.  That will probably make our life easier anyway.

**Comment by mmerklinger** [comment]
The code was migrated to Qt6 in #187. The latest version `2.1.5` includes the Qt6 UI.
